# Generated by Django 5.2.4 on 2025-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryfilmproduct',
            name='factory_judgment',
            field=models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('pending', '待判定'), ('no_standard', '无标准')], default='pending', max_length=50, null=True, verbose_name='出厂判定'),
        ),
        migrations.AlterField(
            model_name='dryfilmproduct',
            name='internal_judgment',
            field=models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('pending', '待判定'), ('no_standard', '无标准')], default='pending', max_length=50, null=True, verbose_name='内控判定'),
        ),
    ]
