# Generated by Django 5.2.4 on 2025-08-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0002_alter_dryfilmproduct_factory_judgment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dryfilmstandard',
            options={},
        ),
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='inside_specifications',
        ),
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='maintainer',
        ),
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='outside_specifications',
        ),
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='resp_persional',
        ),
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='updata_date',
        ),
        migrations.AddField(
            model_name='dryfilmstandard',
            name='config_json',
            field=models.JSONField(null=True, verbose_name='配置参数'),
        ),
        migrations.AddField(
            model_name='dryfilmstandard',
            name='operator',
            field=models.CharField(max_length=50, null=True, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='dryfilmstandard',
            name='product_name',
            field=models.CharField(max_length=100, null=True, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='dryfilmstandard',
            name='production_date',
            field=models.DateField(null=True, verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='dryfilmstandard',
            table=None,
        ),
    ]
