# Generated by Django 5.2.4 on 2025-08-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0003_alter_dryfilmstandard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='change_log',
        ),
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
