# Generated by Django 5.2.4 on 2025-08-05 03:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0004_remove_dryfilmstandard_change_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='dryfilmstandard',
            name='production_date',
        ),
        migrations.AddField(
            model_name='dryfilmstandard',
            name='change_log',
            field=models.JSONField(default=list, verbose_name='变更日志'),
        ),
        migrations.AddField(
            model_name='dryfilmstandard',
            name='producer',
            field=models.CharField(max_length=50, null=True, verbose_name='编制人'),
        ),
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='config_json',
            field=models.JSONField(null=True, verbose_name='产品标准'),
        ),
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
