# Generated by Django 5.2.4 on 2025-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_app', '0005_remove_dryfilmstandard_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryfilmstandard',
            name='product_name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='产品名称'),
        ),
    ]
